---
deployment:
  tasks:
    - export DEPLOYPATH=/home/freizeit/tschardonnay.eu
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R _site $DEPLOYPATH
    - /bin/cp index.html $DELOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
