name: Deploy Eleventy Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy Assets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#      - name: List directory contents
#        run: ls -la .github/workflows/
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh syncflux@${{ secrets.SERVER_IP }}
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: yarn install
      - name: Build the site
#        run: npx @11ty/eleventy
#        run: npm run build
        run: yarn build        
#      - name: Run deploy script
#        run: |
#          ssh syncflux@${{ secrets.SERVER_IP }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh
      - name: Deploy to GitHub
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site